---
abstract: 'SMS::Send backend for Twilio API'
author:
  - 'Michiel Beijen <michiel.beijen@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.020
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SMS-Send-Twilio
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  JSON::PP: 2.27101
  SMS::Send: 1.00
  WWW::Twilio::API: 0.15
  parent: 0.220
  perl: 5.008005
resources:
  bugtracker: https://github.com/mbeijen/SMS-Send-Twilio/issues
  homepage: https://github.com/mbeijen/SMS-Send-Twilio
  repository: https://github.com/mbeijen/SMS-Send-Twilio.git
version: 0.12
